# heavily based on https://github.com/aig787/cargo-udeps-action
name: "cargo-udeps"
description: "Detect unused dependencies in your Rust project"

inputs:
  version:
    description: "The version of `cargo-udeps` to install"
    required: true
    default: ""
  target:
    description: "The binary target to download"
    required: true
    default: "x86_64-unknown-linux-gnu"
  arguments:
    required: false
    description: "The arguments to pass to `cargo-udeps`"
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        gh release download ${{ inputs.version }} -p '*-${{ inputs.target }}.tar.gz' -O - -R est31/cargo-udeps
        | tar -xz -C ~/.cargo/bin/ --strip-components=2 ./cargo-udeps-*/cargo-udeps
      shell: bash
    - run: |
        rustup toolchain install nightly
        rustup default nightly
      shell: bash
    - run: cargo udeps ${{ inputs.arguments }}
      shell: bash
