name: "Cargo Cache"
description: "Caches and restore your Rust build artefacts"
inputs:
  policy:
    description: "Whether to just 'pull', 'push' or 'push-pull' the cache"
    default: push-pull
  key:
    description: "Prefix of the key to be used"
    default: cargo

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: 'actions/cache@v3'
      if: ${{ inputs.policy == 'push-pull' }}
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/target/
        key: ${{ key }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-

    - uses: 'actions/cache/restore@v3'
      if: ${{ inputs.policy == 'pull' }}
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/target/
        key: ${{ key }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-

    - uses: 'actions/cache/save@v3'
      if: ${{ inputs.policy == 'push' }}
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/target/
        key: ${{ key }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}

