name: CI Standard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cargo-cache
    - run: cargo build --all-features --all-targets --release

  format:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cargo-cache
      with:
        policy: pull
    - run: cargo fmt --all -- --check

  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cargo-cache
      with:
        policy: pull
    - run: cargo check --all-features --all-targets

  clippy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cargo-cache
      with:
        policy: pull
    - run: cargo clippy --all-features --all-targets -- --deny clippy::all

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cargo-cache
      with:
        policy: pull
    - run: cargo test --all-features --all-targets

  deny:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cargo-cache
      with:
        policy: pull
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check
        arguments: --all-features

  udeps:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cargo-cache
      with:
        policy: pull
    - run: |
        wget https://github.com/est31/cargo-udeps/releases/download/v0.1.40/cargo-udeps-v0.1.40-x86_64-unknown-linux-gnu.tar.gz
        tar xzf cargo-udeps-v0.1.40-x86_64-unknown-linux-gnu.tar.gz
        mv cargo-udeps-v0.1.40-x86_64-unknown-linux-gnu/cargo-udeps ~/.cargo/bin/cargo-udeps
    - run: |
        rustup toolchain install nightly
        rustup default nightly
    - run: cargo udeps --all-features --all-targets
